const microCParser = require('./parser');
const { arithmeticBinopExpression, 
        arithmeticExpression,
        arrayDeclaration,
        arrayIdentifier,
        assignmentNode,
        booleanBinopExpression,
        booleanExpression,
        booleanLiteral,
        ifElseNode,
        ifNode,
        intDeclaration,
        integerLiteral,
        readNode,
        recordDeclaration,
        recordIdentifier,
        relationalExpression,
        varIdentifier,
        whileNode,
        writeNode, 
    } = require('./../ast/nodes');

microCParser.parser.yy = {
    arithmeticBinopExpression, 
    arithmeticExpression,
    arrayDeclaration,
    arrayIdentifier,
    assignmentNode,
    booleanBinopExpression,
    booleanExpression,
    booleanLiteral,
    ifElseNode,
    ifNode,
    intDeclaration,
    integerLiteral,
    readNode,
    recordDeclaration,
    recordIdentifier,
    relationalExpression,
    varIdentifier,
    whileNode,
    writeNode, 
}

module.exports = microCParser;